GET http://localhost:3003/api/blogs/
###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "This is gist blogger",
    "author": "Nabeel Nabeelah",
    "url": "www.testing.com",
    "likes" : 0
}
###

DELETE http://localhost:3003/api/blogs/6367b89b7b904941388a92c0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYzNjZkMTQxZTQzODZjY2U3OTE0ZTMxMyIsImlhdCI6MTY3MzAxNTMzMywiZXhwIjoxNjczMDE4OTMzfQ.WfJ-UaSK3MgHg4M8BBbusAII-Eu1aiUu84tNpkEv-Nc
###

PUT http://localhost:3003/api/blogs/632eefd66b05eaf2d22454c3
Content-Type: application/json

{
    "title": "Updated Title: Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 3
}

####
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "Ball pit blogger",
    "author": "Odia Ajuri",
    "url": "www.ck.com",
    "likes" : 1,
    "userId":"6366d141e4386cce7914e313"
}

###
post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZHJvb3QiLCJpZCI6IjYzNjZkMTQxZTQzODZjY2U3OTE0ZTMxNSIsImlhdCI6MTY4NDMyNzU1MCwiZXhwIjoxNjg0MzMxMTUwfQ.5hPuDRQYBF27qSt24b5iIwyT2Xt1fIYqwkNXaQKposo

{
    "title": "Blog create with token",
    "author": "Chinua Achebe",
    "url": "http://achebe.chinua.com",
    "likes": 17
}
###
post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZHJvb3QiLCJpZCI6IjYzNjZkMTQxZTQzODZjY2U3OTE0ZTMxNSIsImlhdCI6MTY4NDMyNzU1MCwiZXhwIjoxNjg0MzMxMTUwfQ.5hPuDRQYBF27qSt24b5iIwyT2Xt1fIYqwkNXaQKposo

{
    "title": "",
    "author": "",
    "url": ""
    
}
