GET http://localhost:3003/api/blogs/
###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title" : "This is gist blogger",
    "author": "Nabeel Nabeelah",
    "url": "www.testing.com",
    "likes" : 0
}
###

DELETE http://localhost:3003/api/blogs/6320d085ec587af35beec81e
###

PUT http://localhost:3003/api/blogs/632eefd66b05eaf2d22454c3
Content-Type: application/json

{
    "title": "Updated Title: Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 1
}