pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
                sh 'echo $USER'
                sh 'whoami' 
                dir('part4-backend-blog'){
                
                    sh 'npm install'
                }               
               
                
                
                
                
            }
        }
    }
}