pipeline {
    agent any
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
                sh 'echo $USER'
                sh 'whoami'                
                sh 'cd /var/lib/jenkins/workspace/jimi-first-pipeline/part4-backend-blog'
                sh 'pwd'
                sh 'npm install'
                
                
            }
        }
    }
}