GET http://localhost:3001/api/notes/63297c9a5d712c4453dead6a
###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "JS is not Life"

    
}
###
DELETE http://localhost:3001/api/notes/6317b579538b8a8abbeec691
###

PUT http://localhost:3001/api/notes/63297c9a5d712c4453dead6d
Content-Type: application/json

{
    "content": "Async not working with update",
    "important": true
  }